<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Propnex.Poster.Dtos\Propnex.Poster.Dtos\Propnex.Poster.Dtos.csproj" />
    <ProjectReference Include="..\Propnex.Poster.PropertyGuru\Propnex.Poster.PropertyGuru.csproj" />
    <ProjectReference Include="..\Propnex.Poster.Share\Propnex.Poster.Share.csproj" />
  </ItemGroup>

</Project>
