// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Propnex.Poster.PropertyGuru.Listing.V2;
//
//    var project = Project.FromJson(jsonString);

namespace Propnex.Poster.PropertyGuru.Mobile.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Propnex.Poster.PropertyGuru.Listing.V2;


    public class Location
    {
        /// <summary>
        /// Lat
        /// </summary>
        public double lat { get; set; }
        /// <summary>
        /// Lon
        /// </summary>
        public double lon { get; set; }
    }

    public class Addresses
    {
        /// <summary>
        /// singapore
        /// </summary>
        public string country { get; set; }
        /// <summary>
        /// Estate_code
        /// </summary>
        public string estate_code { get; set; }
        /// <summary>
        /// 1.27352457327214540
        /// </summary>
        public string latitude { get; set; }
        /// <summary>
        /// 154674
        /// </summary>
        public string external_id { get; set; }
        /// <summary>
        /// Localised_street_name
        /// </summary>
        public string localised_street_name { get; set; }
        /// <summary>
        /// Bernam Street
        /// </summary>
        public string street_name { get; set; }
        /// <summary>
        /// 1
        /// </summary>
        public string street_no { get; set; }
        /// <summary>
        /// 103.84365640636763000
        /// </summary>
        public string longitude { get; set; }

        public string postal_code { get; set; }
    }



    public class PropertyType
    {
        /// <summary>
        /// Property_group
        /// </summary>
        public CodeName property_group { get; set; }
        /// <summary>
        /// Property_sub_group
        /// </summary>
        public CodeName property_sub_group { get; set; }
        /// <summary>
        /// Property_type
        /// </summary>
        public CodeName property_type { get; set; }
    }

    public class DerivedInfo
    {
        /// <summary>
        /// Total_floors
        /// </summary>
        public string total_floors { get; set; }
        /// <summary>
        /// Total_units
        /// </summary>
        public string total_units { get; set; }
        /// <summary>
        /// Property_type
        /// </summary>
        public PropertyType property_type { get; set; }
    }

    public partial class Project
    {
        /// <summary>
        /// Description
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// MCC Land (Singapore) Pte Ltd
        /// </summary>
        public string developer_name { get; set; }
        /// <summary>
        /// Id
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// One Bernam
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// Property_id
        /// </summary>
        public int property_id { get; set; }
        /// <summary>
        /// Bernam Street
        /// </summary>
        public string streetname { get; set; }
        /// <summary>
        /// 1
        /// </summary>
        public string streetnumber { get; set; }
        /// <summary>
        /// Tenure
        /// </summary>
        public CodeName tenure { get; set; }
        /// <summary>
        /// L99
        /// </summary>
        public string tenure_code { get; set; }
        /// <summary>
        /// 078852
        /// </summary>
        public string postcode { get; set; }
        /// <summary>
        /// Location
        /// </summary>
        public Location location { get; set; }
        /// <summary>
        /// 1UPC
        /// </summary>
        public string project_status_code { get; set; }
        /// <summary>
        /// CONDO
        /// </summary>
        public string property_type_code { get; set; }
        /// <summary>
        /// N
        /// </summary>
        public string property_type_group { get; set; }
        /// <summary>
        /// D02
        /// </summary>
        public string district_code { get; set; }
        /// <summary>
        /// Addresses
        /// </summary>
        public List<Addresses> addresses { get; set; }
        /// <summary>
        /// Derived_info
        /// </summary>
        public DerivedInfo derived_info { get; set; }
    }


    public partial class Project
    {
        public static Project FromJson(string json) => JsonConvert.DeserializeObject<Project>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Project self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
