version: '3.4'

services:
  propnex.poster.console:
    image: ${DOCKER_REGISTRY-}propnex_poster_console
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - propnex_poster
    volumes:
      - ./app:/app
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
networks:
    propnex_poster:
        name: common
        external: true
volumes:
    propnex_poster:
        driver: local